# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [1]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001,size=(1000,20))

# print the shape of X
print('X = \n',X)

X = 
 [[3855 4927 3671 ... 3767 4060 2548]
 [4570 3048  143 ... 1465  233 4473]
 [4131   30 3582 ...  870  366 4435]
 ...
 [2764 4296 3713 ... 3570 3452 4489]
 [1802 2833  677 ... 2435 4613 4707]
 [2619 2407 2225 ...  510 4821  727]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [2]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [3]:
# Print the shape of ave_cols
print('Average of the values in each column = \n',ave_cols)

# Print the shape of std_cols
print('Standard Deviation of the values in each column = \n',std_cols)

Average of the values in each column = 
 [2599.751 2537.496 2572.003 2479.215 2426.301 2448.624 2479.155 2444.582
 2458.121 2444.53  2520.681 2515.284 2471.024 2520.73  2449.373 2493.018
 2528.013 2439.491 2515.825 2407.041]
Standard Deviation of the values in each column = 
 [1454.41840438 1429.26762364 1458.64246716 1400.83385409 1482.42472537
 1442.24561661 1448.75956286 1396.4773379  1432.53953536 1438.24734142
 1475.76730186 1456.36440404 1420.95467466 1419.05365195 1427.47032749
 1433.30306135 1442.19132809 1426.8549926  1429.75425314 1405.86477775]


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [4]:
# Mean normalize X
X_norm = (X - ave_cols)/std_cols

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [5]:
# Print the average of all the values of X_norm
print('Average of all the values of X_norm = ',X_norm)

# Print the average of the minimum value in each column of X_norm
print('Average of the minimum value in each column of X_norm = ',X_norm.min(axis=0))

# Print the average of the maximum value in each column of X_norm
print('Average of the maximum value in each column of X_norm = ',X_norm.max(axis=0))

Average of all the values of X_norm =  [[ 0.86305907  1.67183805  0.75343823 ...  0.93037415  1.08002826
   0.10026498]
 [ 1.35466451  0.35717873 -1.66524906 ... -0.68296429 -1.59665551
   1.46952896]
 [ 1.05282565 -1.75439222  0.69242259 ... -1.09996531 -1.50363253
   1.44249933]
 ...
 [ 0.11293105  1.2303532   0.78223213 ...  0.79230826  0.65478036
   1.48090985]
 [-0.54850172  0.20675204 -1.29915524 ... -0.00314748  1.46680802
   1.63597455]
 [ 0.01323484 -0.0913027  -0.23789449 ... -1.35226846  1.61228756
  -1.19502318]]
Average of the minimum value in each column of X_norm =  [-1.78542226 -1.77468233 -1.76054315 -1.7669583  -1.6367111  -1.69709235
 -1.71122598 -1.74695424 -1.71242813 -1.69340136 -1.70737012 -1.72297812
 -1.73687736 -1.77564111 -1.71588365 -1.73586317 -1.7528971  -1.70339033
 -1.75822173 -1.70502956]
Average of the maximum value in each column of X_norm =  [1.64825266 1.72291316 1.6618171  1.7980612  1.73209402 1.76764344
 1.73931207 1.82489034 1.77019826 1.7712322

You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [6]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([0, 4, 1, 3, 2])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [7]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [8]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.

# Create a Training Set
X_train = X_norm[row_indices[:600]]

# Create a Cross Validation Set
X_crossVal = X_norm[row_indices[600:800]]

# Create a Test Set
X_test = X_norm[row_indices[800:1001]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [9]:
# Print the shape of X_train
print('Shape of X_train = ',X_train.shape)

# Print the shape of X_crossVal
print('Shape of X_crossVal = ',X_crossVal.shape)

# Print the shape of X_test
print('Shape of X_test = ',X_test.shape)

Shape of X_train =  (600, 20)
Shape of X_crossVal =  (200, 20)
Shape of X_test =  (200, 20)
